name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python: 3.11.1
            django: 4.1.6
            djangorestframework: 3.14.0
          - python: 3.9.16
            django: 3.2.17
            djangorestframework: 3.13.0
          - python: 3.7.15
            django: 2.2.28
            djangorestframework: 3.9.4
          - python: 3.5.10
            django: 1.11.29
            djangorestframework: 3.9.4
          - python: 2.7.18
            django: 1.8.19
            djangorestframework: 3.6.4
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: >-
          python -m pip 
          install --upgrade 
          pip 
          'setuptools<56'
          wheel 
          flake8 
          'Django==${{ matrix.django }}'
          'djangorestframework==${{ matrix.djangorestframework }}'
      - name: Run Tests
        run: |
          ./runtests.sh
